language: cpp
compiler: gcc
before_install:
  - sudo add-apt-repository ppa:boost-latest/ppa -y
  - sudo apt-get update -qq
install:
  - sudo apt-get install google-mock boost1.55
script:
  - mkdir -p lib
  - (cd lib && make gtest.a -f /usr/share/doc/libgtest-dev/examples/make/Makefile)
  - make all
